config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :persons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @persons = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.save
    redirect_to @person
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :birthdate, :status)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/index.html.erb
<h1>Library's Persons</h1>
<table>
  <thead>
    <tr>
      <td>User</td>
      <td>Birthday</td>
      <td>Estatus</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @persons.each do |person| %>
      <tr>
        <td><%= "#{person.first_name} #{person.last_name}" %></td>
        <td><%= person.birthday %></td>
        <td><%= person.status? ? "A" : "I" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/persons/new.html.erb
<h1>New Person</h1>

<%= form_for :person, url: persons_path  do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br>
  </p>
  <p>
    <%= f.label :birthdate %><br>
    <%= f.text_field :birthdate %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </p>
  <p>
    <%= f.submit("Create") %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to library on line</h1>

<ul>
  <li><%= link_to "System's person", persons_path %></li>
</ul>